settings:
  name: "Replication"
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: Back to Cloud Manager documentation
      url: https://docs.netapp.com/us-en/cloud-manager-family
    - title: Replication docs
      url: /index.html
    - title: Release notes
      url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about the Replication service
          url: /concept-replication.html
        - title: Set up data replication
          url: /task-replicating-data.html
    - title: Manage data replication
      url: /task-managing-replication.html
    - title: Concepts
      entries:
        - title: Learn about replication policies
          url: /concept-replication-policies.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
homepage:
  tiles:
    - title: Get started
      links:
        - title: title
          url: page.html
        - title: title
          url: page.html
        - title: title
          url: page.html
    - title: tile name
      links:
        - title: title
          url: page.html
        - title: title
          url: page.html
        - title: title
          url: page.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: Cloud Central blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
