settings:
  name: BlueXP replication
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: BlueXP replication docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
    - title: Get started
      entries:
        - title: Learn about BlueXP replication
          url: /concept-replication.html
        - title: Set up data replication
          url: /task-replicating-data.html
    - title: Manage data replication
      url: /task-managing-replication.html
    - title: Learn more
      entries:
        - title: Learn about replication policies
          url: /concept-replication-policies.html
        - title: Learn about backup policies
          url: /concept-backup-policies.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family
homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about BlueXP replication
          url: concept-replication.html
        - title: Set up data replication
          url: task-replicating-data.html
    - title: Use BlueXP replication
      links:
        - title: Manage data replication
          url: task-managing-replication.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: BlueXP blog
          url: https://cloud.netapp.com/blog
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
